# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PopUpWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 617)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.MainDataTimeWidget = PlotWidget(self.centralwidget)
        self.MainDataTimeWidget.setObjectName("MainDataTimeWidget")
        self.horizontalLayout_4.addWidget(self.MainDataTimeWidget)
        self.MainDataFFTWidget = PlotWidget(self.centralwidget)
        self.MainDataFFTWidget.setObjectName("MainDataFFTWidget")
        self.horizontalLayout_4.addWidget(self.MainDataFFTWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.SavedData1TimeWidget = PlotWidget(self.centralwidget)
        self.SavedData1TimeWidget.setObjectName("SavedData1TimeWidget")
        self.horizontalLayout_5.addWidget(self.SavedData1TimeWidget)
        self.SavedData1FFTWidget = PlotWidget(self.centralwidget)
        self.SavedData1FFTWidget.setObjectName("SavedData1FFTWidget")
        self.horizontalLayout_5.addWidget(self.SavedData1FFTWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.LoadFiletoWidget1Button = QtWidgets.QPushButton(self.centralwidget)
        self.LoadFiletoWidget1Button.setObjectName("LoadFiletoWidget1Button")
        self.horizontalLayout_2.addWidget(self.LoadFiletoWidget1Button)
        self.ClearWidget1Button = QtWidgets.QPushButton(self.centralwidget)
        self.ClearWidget1Button.setObjectName("ClearWidget1Button")
        self.horizontalLayout_2.addWidget(self.ClearWidget1Button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.SavedData2TimeWidget = PlotWidget(self.centralwidget)
        self.SavedData2TimeWidget.setObjectName("SavedData2TimeWidget")
        self.horizontalLayout_6.addWidget(self.SavedData2TimeWidget)
        self.SavedData2FFTWidget = PlotWidget(self.centralwidget)
        self.SavedData2FFTWidget.setObjectName("SavedData2FFTWidget")
        self.horizontalLayout_6.addWidget(self.SavedData2FFTWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.LoadFiletoWidget2Button = QtWidgets.QPushButton(self.centralwidget)
        self.LoadFiletoWidget2Button.setObjectName("LoadFiletoWidget2Button")
        self.horizontalLayout_3.addWidget(self.LoadFiletoWidget2Button)
        self.ClearWidget2Button = QtWidgets.QPushButton(self.centralwidget)
        self.ClearWidget2Button.setObjectName("ClearWidget2Button")
        self.horizontalLayout_3.addWidget(self.ClearWidget2Button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Play"))
        self.LoadFiletoWidget1Button.setText(_translate("MainWindow", "Load A File"))
        self.ClearWidget1Button.setText(_translate("MainWindow", "Clear Plot"))
        self.pushButton_2.setText(_translate("MainWindow", "Play"))
        self.LoadFiletoWidget2Button.setText(_translate("MainWindow", "Load A File"))
        self.ClearWidget2Button.setText(_translate("MainWindow", "Clear Plot"))

from pyqtgraph import PlotWidget
