# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1191, 777)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.MainDataTimeWidget = PlotWidget(self.centralwidget)
        self.MainDataTimeWidget.setObjectName("MainDataTimeWidget")
        self.horizontalLayout_2.addWidget(self.MainDataTimeWidget)
        self.MainDataFFTWidget = PlotWidget(self.centralwidget)
        self.MainDataFFTWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.MainDataFFTWidget.setObjectName("MainDataFFTWidget")
        self.horizontalLayout_2.addWidget(self.MainDataFFTWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.OpenFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenFileButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.OpenFileButton.setObjectName("OpenFileButton")
        self.verticalLayout_3.addWidget(self.OpenFileButton)
        self.PlayButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlayButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.PlayButton.setObjectName("PlayButton")
        self.verticalLayout_3.addWidget(self.PlayButton)
        self.StopButton = QtWidgets.QPushButton(self.centralwidget)
        self.StopButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.StopButton.setObjectName("StopButton")
        self.verticalLayout_3.addWidget(self.StopButton)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setMaximumSize(QtCore.QSize(200, 20))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.SaveMode = QtWidgets.QComboBox(self.centralwidget)
        self.SaveMode.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SaveMode.setObjectName("SaveMode")
        self.SaveMode.addItem("")
        self.SaveMode.addItem("")
        self.SaveMode.addItem("")
        self.verticalLayout_3.addWidget(self.SaveMode)
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SaveButton.setObjectName("SaveButton")
        self.verticalLayout_3.addWidget(self.SaveButton)
        self.LoadFromAQuickSaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoadFromAQuickSaveButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.LoadFromAQuickSaveButton.setObjectName("LoadFromAQuickSaveButton")
        self.verticalLayout_3.addWidget(self.LoadFromAQuickSaveButton)
        self.CompareButton = QtWidgets.QPushButton(self.centralwidget)
        self.CompareButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.CompareButton.setObjectName("CompareButton")
        self.verticalLayout_3.addWidget(self.CompareButton)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(200, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.WindowMode = QtWidgets.QComboBox(self.centralwidget)
        self.WindowMode.setMaximumSize(QtCore.QSize(200, 16777215))
        self.WindowMode.setObjectName("WindowMode")
        self.WindowMode.addItem("")
        self.WindowMode.addItem("")
        self.WindowMode.addItem("")
        self.verticalLayout_3.addWidget(self.WindowMode)
        self.ApplyEqualizerButton = QtWidgets.QPushButton(self.centralwidget)
        self.ApplyEqualizerButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ApplyEqualizerButton.setObjectName("ApplyEqualizerButton")
        self.verticalLayout_3.addWidget(self.ApplyEqualizerButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.OnOff = QtWidgets.QPushButton(self.centralwidget)
        self.OnOff.setObjectName("OnOff")
        self.verticalLayout_4.addWidget(self.OnOff)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.Band1Slider = QtWidgets.QSlider(self.centralwidget)
        self.Band1Slider.setStyleSheet("margin:auto;")
        self.Band1Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band1Slider.setObjectName("Band1Slider")
        self.verticalLayout_5.addWidget(self.Band1Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.Band2Slider = QtWidgets.QSlider(self.centralwidget)
        self.Band2Slider.setStyleSheet("margin:auto;")
        self.Band2Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band2Slider.setObjectName("Band2Slider")
        self.verticalLayout_9.addWidget(self.Band2Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_10.addWidget(self.label_6)
        self.Band3Slider = QtWidgets.QSlider(self.centralwidget)
        self.Band3Slider.setStyleSheet("margin:auto;")
        self.Band3Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band3Slider.setObjectName("Band3Slider")
        self.verticalLayout_10.addWidget(self.Band3Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_12.addWidget(self.label_8)
        self.Band4Slider = QtWidgets.QSlider(self.centralwidget)
        self.Band4Slider.setStyleSheet("margin:auto;")
        self.Band4Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band4Slider.setObjectName("Band4Slider")
        self.verticalLayout_12.addWidget(self.Band4Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_15.addWidget(self.label_11)
        self.Band5Slider = QtWidgets.QSlider(self.centralwidget)
        self.Band5Slider.setStyleSheet("margin:auto;")
        self.Band5Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band5Slider.setObjectName("Band5Slider")
        self.verticalLayout_15.addWidget(self.Band5Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_15)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_14.addWidget(self.label_10)
        self.Band6Slider = QtWidgets.QSlider(self.centralwidget)
        self.Band6Slider.setStyleSheet("margin:auto;")
        self.Band6Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band6Slider.setObjectName("Band6Slider")
        self.verticalLayout_14.addWidget(self.Band6Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_14)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.Band7Slider = QtWidgets.QSlider(self.centralwidget)
        self.Band7Slider.setStyleSheet("margin:auto;")
        self.Band7Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band7Slider.setObjectName("Band7Slider")
        self.verticalLayout_13.addWidget(self.Band7Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_13)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.Band8Slider = QtWidgets.QSlider(self.centralwidget)
        self.Band8Slider.setStyleSheet("margin:auto;")
        self.Band8Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band8Slider.setObjectName("Band8Slider")
        self.verticalLayout_8.addWidget(self.Band8Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.Band9Slider = QtWidgets.QSlider(self.centralwidget)
        self.Band9Slider.setStyleSheet("margin:auto;")
        self.Band9Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band9Slider.setObjectName("Band9Slider")
        self.verticalLayout_11.addWidget(self.Band9Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.Band10Slider = QtWidgets.QSlider(self.centralwidget)
        self.Band10Slider.setStyleSheet("margin:auto;")
        self.Band10Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band10Slider.setObjectName("Band10Slider")
        self.verticalLayout_7.addWidget(self.Band10Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_3.addLayout(self.verticalLayout_16)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_17.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1191, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OpenFileButton.setText(_translate("MainWindow", "Open File"))
        self.PlayButton.setText(_translate("MainWindow", "Play"))
        self.StopButton.setText(_translate("MainWindow", "Stop"))
        self.label_12.setText(_translate("MainWindow", "Save Mode:"))
        self.SaveMode.setItemText(0, _translate("MainWindow", "To A File"))
        self.SaveMode.setItemText(1, _translate("MainWindow", "QuickSave1"))
        self.SaveMode.setItemText(2, _translate("MainWindow", "QuickSave2"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.LoadFromAQuickSaveButton.setText(_translate("MainWindow", "Load From Save"))
        self.CompareButton.setText(_translate("MainWindow", "Open The Comparer"))
        self.label_2.setText(_translate("MainWindow", "Window Mode:"))
        self.WindowMode.setItemText(0, _translate("MainWindow", "Rectangular"))
        self.WindowMode.setItemText(1, _translate("MainWindow", "Hamming"))
        self.WindowMode.setItemText(2, _translate("MainWindow", "Hanning"))
        self.ApplyEqualizerButton.setText(_translate("MainWindow", "Apply Equalizer"))
        self.OnOff.setText(_translate("MainWindow", "ON"))
        self.label.setText(_translate("MainWindow", "30 Hz"))
        self.label_5.setText(_translate("MainWindow", "60 Hz"))
        self.label_6.setText(_translate("MainWindow", "120 Hz"))
        self.label_8.setText(_translate("MainWindow", "230 Hz"))
        self.label_11.setText(_translate("MainWindow", "450 Hz"))
        self.label_10.setText(_translate("MainWindow", "900 KHz"))
        self.label_9.setText(_translate("MainWindow", "1.8 KHz"))
        self.label_4.setText(_translate("MainWindow", "3.7 KHz"))
        self.label_7.setText(_translate("MainWindow", "7.5 KHz"))
        self.label_3.setText(_translate("MainWindow", "15 KHz"))

from pyqtgraph import PlotWidget
