# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1259, 947)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.TabViews = QtWidgets.QTabWidget(self.centralwidget)
        self.TabViews.setObjectName("TabViews")
        self.SignalViewer = QtWidgets.QWidget()
        self.SignalViewer.setObjectName("SignalViewer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.SignalViewer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.SignalViewer)
        self.label_13.setMinimumSize(QtCore.QSize(200, 0))
        self.label_13.setMaximumSize(QtCore.QSize(200, 20))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.OpenFileButton = QtWidgets.QPushButton(self.SignalViewer)
        self.OpenFileButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.OpenFileButton.setObjectName("OpenFileButton")
        self.verticalLayout_6.addWidget(self.OpenFileButton)
        self.OpenedDataPlayButton = QtWidgets.QPushButton(self.SignalViewer)
        self.OpenedDataPlayButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.OpenedDataPlayButton.setObjectName("OpenedDataPlayButton")
        self.verticalLayout_6.addWidget(self.OpenedDataPlayButton)
        self.OpenedDataStopButton = QtWidgets.QPushButton(self.SignalViewer)
        self.OpenedDataStopButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.OpenedDataStopButton.setObjectName("OpenedDataStopButton")
        self.verticalLayout_6.addWidget(self.OpenedDataStopButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.OpenedDataTimeWidget = PlotWidget(self.SignalViewer)
        self.OpenedDataTimeWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.OpenedDataTimeWidget.setObjectName("OpenedDataTimeWidget")
        self.horizontalLayout_4.addWidget(self.OpenedDataTimeWidget)
        self.OpenedDataFFTWidget = PlotWidget(self.SignalViewer)
        self.OpenedDataFFTWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.OpenedDataFFTWidget.setObjectName("OpenedDataFFTWidget")
        self.horizontalLayout_4.addWidget(self.OpenedDataFFTWidget)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_14 = QtWidgets.QLabel(self.SignalViewer)
        self.label_14.setMinimumSize(QtCore.QSize(200, 0))
        self.label_14.setMaximumSize(QtCore.QSize(200, 20))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_18.addWidget(self.label_14)
        self.MainDataPlayButton = QtWidgets.QPushButton(self.SignalViewer)
        self.MainDataPlayButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.MainDataPlayButton.setObjectName("MainDataPlayButton")
        self.verticalLayout_18.addWidget(self.MainDataPlayButton)
        self.MainDataStopButton = QtWidgets.QPushButton(self.SignalViewer)
        self.MainDataStopButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.MainDataStopButton.setObjectName("MainDataStopButton")
        self.verticalLayout_18.addWidget(self.MainDataStopButton)
        self.horizontalLayout.addLayout(self.verticalLayout_18)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.MainDataTimeWidget = PlotWidget(self.SignalViewer)
        self.MainDataTimeWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.MainDataTimeWidget.setObjectName("MainDataTimeWidget")
        self.horizontalLayout_7.addWidget(self.MainDataTimeWidget)
        self.MainDataFFTWidget = PlotWidget(self.SignalViewer)
        self.MainDataFFTWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.MainDataFFTWidget.setObjectName("MainDataFFTWidget")
        self.horizontalLayout_7.addWidget(self.MainDataFFTWidget)
        self.horizontalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_15 = QtWidgets.QLabel(self.SignalViewer)
        self.label_15.setMinimumSize(QtCore.QSize(200, 0))
        self.label_15.setMaximumSize(QtCore.QSize(200, 20))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_19.addWidget(self.label_15)
        self.SavedData1PlayButton = QtWidgets.QPushButton(self.SignalViewer)
        self.SavedData1PlayButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SavedData1PlayButton.setObjectName("SavedData1PlayButton")
        self.verticalLayout_19.addWidget(self.SavedData1PlayButton)
        self.SavedData1StopButton = QtWidgets.QPushButton(self.SignalViewer)
        self.SavedData1StopButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SavedData1StopButton.setObjectName("SavedData1StopButton")
        self.verticalLayout_19.addWidget(self.SavedData1StopButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout_19)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.SavedData1TimeWidget = PlotWidget(self.SignalViewer)
        self.SavedData1TimeWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.SavedData1TimeWidget.setObjectName("SavedData1TimeWidget")
        self.horizontalLayout_8.addWidget(self.SavedData1TimeWidget)
        self.SavedData1FFTWidget = PlotWidget(self.SignalViewer)
        self.SavedData1FFTWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.SavedData1FFTWidget.setObjectName("SavedData1FFTWidget")
        self.horizontalLayout_8.addWidget(self.SavedData1FFTWidget)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_16 = QtWidgets.QLabel(self.SignalViewer)
        self.label_16.setMinimumSize(QtCore.QSize(200, 0))
        self.label_16.setMaximumSize(QtCore.QSize(200, 20))
        self.label_16.setObjectName("label_16")
        self.verticalLayout_20.addWidget(self.label_16)
        self.SavedData2PlayButton = QtWidgets.QPushButton(self.SignalViewer)
        self.SavedData2PlayButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SavedData2PlayButton.setObjectName("SavedData2PlayButton")
        self.verticalLayout_20.addWidget(self.SavedData2PlayButton)
        self.SavedData2StopButton = QtWidgets.QPushButton(self.SignalViewer)
        self.SavedData2StopButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SavedData2StopButton.setObjectName("SavedData2StopButton")
        self.verticalLayout_20.addWidget(self.SavedData2StopButton)
        self.horizontalLayout_9.addLayout(self.verticalLayout_20)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.SavedData2TimeWidget = PlotWidget(self.SignalViewer)
        self.SavedData2TimeWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.SavedData2TimeWidget.setObjectName("SavedData2TimeWidget")
        self.horizontalLayout_10.addWidget(self.SavedData2TimeWidget)
        self.SavedData2FFTWidget = PlotWidget(self.SignalViewer)
        self.SavedData2FFTWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.SavedData2FFTWidget.setObjectName("SavedData2FFTWidget")
        self.horizontalLayout_10.addWidget(self.SavedData2FFTWidget)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Data1ComboBox = QtWidgets.QComboBox(self.SignalViewer)
        self.Data1ComboBox.setObjectName("Data1ComboBox")
        self.Data1ComboBox.addItem("")
        self.Data1ComboBox.addItem("")
        self.Data1ComboBox.addItem("")
        self.Data1ComboBox.addItem("")
        self.horizontalLayout_11.addWidget(self.Data1ComboBox)
        self.CompareToButton = QtWidgets.QPushButton(self.SignalViewer)
        self.CompareToButton.setObjectName("CompareToButton")
        self.horizontalLayout_11.addWidget(self.CompareToButton)
        self.Data2ComboBox = QtWidgets.QComboBox(self.SignalViewer)
        self.Data2ComboBox.setObjectName("Data2ComboBox")
        self.Data2ComboBox.addItem("")
        self.Data2ComboBox.addItem("")
        self.Data2ComboBox.addItem("")
        self.Data2ComboBox.addItem("")
        self.horizontalLayout_11.addWidget(self.Data2ComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.TabViews.addTab(self.SignalViewer, "")
        self.Equalizer = QtWidgets.QWidget()
        self.Equalizer.setObjectName("Equalizer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Equalizer)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.EqualizerDataTimeWidget = PlotWidget(self.Equalizer)
        self.EqualizerDataTimeWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.EqualizerDataTimeWidget.setObjectName("EqualizerDataTimeWidget")
        self.horizontalLayout_6.addWidget(self.EqualizerDataTimeWidget)
        self.EqualizerDataFFTWidget = PlotWidget(self.Equalizer)
        self.EqualizerDataFFTWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.EqualizerDataFFTWidget.setObjectName("EqualizerDataFFTWidget")
        self.horizontalLayout_6.addWidget(self.EqualizerDataFFTWidget)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ResetButton = QtWidgets.QPushButton(self.Equalizer)
        self.ResetButton.setObjectName("ResetButton")
        self.verticalLayout_3.addWidget(self.ResetButton)
        self.CompareToOpenedDataButton = QtWidgets.QPushButton(self.Equalizer)
        self.CompareToOpenedDataButton.setObjectName("CompareToOpenedDataButton")
        self.verticalLayout_3.addWidget(self.CompareToOpenedDataButton)
        self.label_12 = QtWidgets.QLabel(self.Equalizer)
        self.label_12.setMaximumSize(QtCore.QSize(200, 20))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.SaveMode = QtWidgets.QComboBox(self.Equalizer)
        self.SaveMode.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SaveMode.setObjectName("SaveMode")
        self.SaveMode.addItem("")
        self.SaveMode.addItem("")
        self.SaveMode.addItem("")
        self.verticalLayout_3.addWidget(self.SaveMode)
        self.SaveButton = QtWidgets.QPushButton(self.Equalizer)
        self.SaveButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SaveButton.setObjectName("SaveButton")
        self.verticalLayout_3.addWidget(self.SaveButton)
        self.label_2 = QtWidgets.QLabel(self.Equalizer)
        self.label_2.setMaximumSize(QtCore.QSize(200, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.WindowMode = QtWidgets.QComboBox(self.Equalizer)
        self.WindowMode.setMaximumSize(QtCore.QSize(200, 16777215))
        self.WindowMode.setObjectName("WindowMode")
        self.WindowMode.addItem("")
        self.WindowMode.addItem("")
        self.WindowMode.addItem("")
        self.verticalLayout_3.addWidget(self.WindowMode)
        self.ApplyEqualizerButton = QtWidgets.QPushButton(self.Equalizer)
        self.ApplyEqualizerButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ApplyEqualizerButton.setObjectName("ApplyEqualizerButton")
        self.verticalLayout_3.addWidget(self.ApplyEqualizerButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.Equalizer)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.Band1Slider = QtWidgets.QSlider(self.Equalizer)
        self.Band1Slider.setStyleSheet("margin:auto;")
        self.Band1Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band1Slider.setObjectName("Band1Slider")
        self.verticalLayout_5.addWidget(self.Band1Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.Equalizer)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.Band2Slider = QtWidgets.QSlider(self.Equalizer)
        self.Band2Slider.setStyleSheet("margin:auto;")
        self.Band2Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band2Slider.setObjectName("Band2Slider")
        self.verticalLayout_9.addWidget(self.Band2Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.Equalizer)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_10.addWidget(self.label_6)
        self.Band3Slider = QtWidgets.QSlider(self.Equalizer)
        self.Band3Slider.setStyleSheet("margin:auto;")
        self.Band3Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band3Slider.setObjectName("Band3Slider")
        self.verticalLayout_10.addWidget(self.Band3Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.Equalizer)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_12.addWidget(self.label_8)
        self.Band4Slider = QtWidgets.QSlider(self.Equalizer)
        self.Band4Slider.setStyleSheet("margin:auto;")
        self.Band4Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band4Slider.setObjectName("Band4Slider")
        self.verticalLayout_12.addWidget(self.Band4Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.Equalizer)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_15.addWidget(self.label_11)
        self.Band5Slider = QtWidgets.QSlider(self.Equalizer)
        self.Band5Slider.setStyleSheet("margin:auto;")
        self.Band5Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band5Slider.setObjectName("Band5Slider")
        self.verticalLayout_15.addWidget(self.Band5Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_15)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.Equalizer)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_14.addWidget(self.label_10)
        self.Band6Slider = QtWidgets.QSlider(self.Equalizer)
        self.Band6Slider.setStyleSheet("margin:auto;")
        self.Band6Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band6Slider.setObjectName("Band6Slider")
        self.verticalLayout_14.addWidget(self.Band6Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_14)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.Equalizer)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.Band7Slider = QtWidgets.QSlider(self.Equalizer)
        self.Band7Slider.setStyleSheet("margin:auto;")
        self.Band7Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band7Slider.setObjectName("Band7Slider")
        self.verticalLayout_13.addWidget(self.Band7Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_13)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.Equalizer)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.Band8Slider = QtWidgets.QSlider(self.Equalizer)
        self.Band8Slider.setStyleSheet("margin:auto;")
        self.Band8Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band8Slider.setObjectName("Band8Slider")
        self.verticalLayout_8.addWidget(self.Band8Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.Equalizer)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.Band9Slider = QtWidgets.QSlider(self.Equalizer)
        self.Band9Slider.setStyleSheet("margin:auto;")
        self.Band9Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band9Slider.setObjectName("Band9Slider")
        self.verticalLayout_11.addWidget(self.Band9Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.Equalizer)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.Band10Slider = QtWidgets.QSlider(self.Equalizer)
        self.Band10Slider.setStyleSheet("margin:auto;")
        self.Band10Slider.setOrientation(QtCore.Qt.Vertical)
        self.Band10Slider.setObjectName("Band10Slider")
        self.verticalLayout_7.addWidget(self.Band10Slider)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_3.addLayout(self.verticalLayout_16)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.TabViews.addTab(self.Equalizer, "")
        self.verticalLayout_17.addWidget(self.TabViews)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1259, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.TabViews.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_13.setText(_translate("MainWindow", "Opened Data"))
        self.OpenFileButton.setText(_translate("MainWindow", "Open File"))
        self.OpenedDataPlayButton.setText(_translate("MainWindow", "Play"))
        self.OpenedDataStopButton.setText(_translate("MainWindow", "Stop"))
        self.label_14.setText(_translate("MainWindow", "Modified Data"))
        self.MainDataPlayButton.setText(_translate("MainWindow", "Play"))
        self.MainDataStopButton.setText(_translate("MainWindow", "Stop"))
        self.label_15.setText(_translate("MainWindow", "Saved Data 1"))
        self.SavedData1PlayButton.setText(_translate("MainWindow", "Play"))
        self.SavedData1StopButton.setText(_translate("MainWindow", "Stop"))
        self.label_16.setText(_translate("MainWindow", "Saved Data 2"))
        self.SavedData2PlayButton.setText(_translate("MainWindow", "Play"))
        self.SavedData2StopButton.setText(_translate("MainWindow", "Stop"))
        self.Data1ComboBox.setItemText(0, _translate("MainWindow", "Original Data"))
        self.Data1ComboBox.setItemText(1, _translate("MainWindow", "Main Data"))
        self.Data1ComboBox.setItemText(2, _translate("MainWindow", "Quick Save 1"))
        self.Data1ComboBox.setItemText(3, _translate("MainWindow", "Quick Save 2"))
        self.CompareToButton.setText(_translate("MainWindow", "Compare to"))
        self.Data2ComboBox.setItemText(0, _translate("MainWindow", "Original Data"))
        self.Data2ComboBox.setItemText(1, _translate("MainWindow", "Main Data"))
        self.Data2ComboBox.setItemText(2, _translate("MainWindow", "Quick Save 1"))
        self.Data2ComboBox.setItemText(3, _translate("MainWindow", "Quick Save 2"))
        self.TabViews.setTabText(self.TabViews.indexOf(self.SignalViewer), _translate("MainWindow", "Signals Viewer"))
        self.ResetButton.setText(_translate("MainWindow", "Reset"))
        self.CompareToOpenedDataButton.setText(_translate("MainWindow", "Comare with Original Data"))
        self.label_12.setText(_translate("MainWindow", "Save Mode:"))
        self.SaveMode.setItemText(0, _translate("MainWindow", "To A File"))
        self.SaveMode.setItemText(1, _translate("MainWindow", "QuickSave1"))
        self.SaveMode.setItemText(2, _translate("MainWindow", "QuickSave2"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.label_2.setText(_translate("MainWindow", "Window Mode:"))
        self.WindowMode.setItemText(0, _translate("MainWindow", "Rectangular"))
        self.WindowMode.setItemText(1, _translate("MainWindow", "Hamming"))
        self.WindowMode.setItemText(2, _translate("MainWindow", "Hanning"))
        self.ApplyEqualizerButton.setText(_translate("MainWindow", "Apply Equalizer"))
        self.label.setText(_translate("MainWindow", "20 Hz-2 KHz"))
        self.label_5.setText(_translate("MainWindow", "2 KHz-4 KHz"))
        self.label_6.setText(_translate("MainWindow", "4 KHz-6 KHz"))
        self.label_8.setText(_translate("MainWindow", "6 KHz-8 KHz"))
        self.label_11.setText(_translate("MainWindow", "8 KHz-10 KHz"))
        self.label_10.setText(_translate("MainWindow", "10 KHz-12 KHz"))
        self.label_9.setText(_translate("MainWindow", "12 KHz-14 KHz"))
        self.label_4.setText(_translate("MainWindow", "14 KHz-16 KHz"))
        self.label_7.setText(_translate("MainWindow", "16 KHz-18 KHz"))
        self.label_3.setText(_translate("MainWindow", "18 KHz-22 KHz"))
        self.TabViews.setTabText(self.TabViews.indexOf(self.Equalizer), _translate("MainWindow", "Equalizer"))

from pyqtgraph import PlotWidget
